Feature/server bootstrap
edgegap/edgegap-unity-plugin pull request #30
Opened 2024-12-09 15:21 UTC by edge-marge

2025-02-04 21:30 UTC, orcist requested changes
overall great PR! I had a few questions and notes on maintainability for future, take a look and changes/respond please 🙏

2025-02-04 21:30 UTC, orcist commented on Edgegap.asmdef
> +        "GUID:02d6592ab05a444498a83be4f8722ca2"
@edge-marge please what is this referencing?

2025-02-04 21:30 UTC, orcist commented on Editor/EdgegapServerBootstrapMenu.cs
> +        [MenuItem("Assets/Create/Edgegap/Server Bootstrap", priority = 35)]
any reason you chose 35? I saw docs recommend 10 but it seems arbitrary

2025-02-04 21:30 UTC, orcist commented on Editor/EdgegapServerBootstrapMenu.cs
> +                    Debug.LogWarning("No netcode currently selected in the Edgegap plugin. Make sure to select one under \"2. Build your game server.\"");
I suggest removing the reference and just say `No netcode currently selected in the Edgegap plugin, host and port validation skipped.` just in case we decide to reorganize the plugin UI later or change section names.

2025-02-04 21:30 UTC, orcist commented on Editor/EdgegapServerBootstrapMenu.cs
> +                if (string.IsNullOrEmpty(netcode))
please apply early exit pattern, instead of `if-else` check `if` and return after logging the warning. the rest of the code then doesn't need to be indented in the `else` clause ;)

2025-02-04 21:30 UTC, orcist commented on Editor/EdgegapServerBootstrapMenu.cs
> +                                break;
this foreach/break search seems a little fragile, is there any `Find` method or something of the sorts to use instead?

2025-02-04 21:30 UTC, orcist commented on Editor/EdgegapServerBootstrapMenu.cs
> +                        if (scriptType is not null)
to reduce the amount of indentation and nested statements, please flip the condition and use early exit pattern - `if (scriptType is null) { Debug.Log(...); return; }`

2025-02-04 21:30 UTC, orcist commented on Editor/EdgegapServerBootstrapMenu.cs
> +                            Debug.LogWarning("Could not find new script's type.");
this error seems poorly defined, when can this happen? shouldn't we always have some script since the user selected some netcode? if so, shouldn't this be an exception instead of a warning? what happens if I select custom netcode? that shouldn't be an error case

2025-02-04 21:30 UTC, orcist commented on Editor/EdgegapWindowV2.cs
> +            EditorPrefs.DeleteKey(EdgegapWindowMetadata.SELECTED_NETCODE_KEY_STR);
what happens if I sign out, delete my editorprefs key, but keep the file in the project?

2025-02-04 21:30 UTC, orcist commented on Editor/EdgegapWindowV2.cs
> +            List<string> netcodes = Enum.GetValues(typeof(EdgegapWindowMetadata.Netcodes)).Cast<EdgegapWindowMetadata.Netcodes>().Select(v => v.ToString()).ToList();
seems like a long unformatted line, do you have csharpier configured to use? (see [readme](https://github.com/edgegap/edgegap-unity-plugin?tab=readme-ov-file#csharpier-code-formatter)) helps tremendously with auto formatting code for readability

2025-02-04 21:30 UTC, orcist commented on Runtime/Models/ArbitriumPortsMapping.cs
> +using UnityEngine;
probably unneeded import?

2025-02-04 21:30 UTC, orcist commented on Runtime/EdgegapServerBootstrap.cs
> +                if (envEntry.Key.ToString().Contains("ARBITRIUM_"))
use early exit pattern, flip condition to `!envEntry...Contains(...) { continue; }` to remove a level of indentation and improve readability

2025-02-04 21:30 UTC, orcist commented on Runtime/EdgegapServerBootstrap.cs
> +                if (envEntry.Key.ToString().Contains("ARBITRIUM_"))
store `string envKey = envEntry.Key.ToString()` to reuse in if statements, should make this easier to maintain

2025-02-04 21:30 UTC, orcist commented on Runtime/EdgegapServerBootstrap.cs
> +        protected virtual void ValidatePortMapping()
`abstract` may be better than `virtual`, since it will require from compiler that inherited classes implement the method.

2025-02-04 21:30 UTC, orcist commented on Runtime/EdgegapServerBootstrap.cs
> +#if !UNITY_CLIENT && !UNITY_EDITOR
would recommend wrapping the whole `Start` method in this compiler macro, that way the event won't fire. tiny different, just nitpicking :)

2025-02-05 16:05 UTC, edge-marge commented on Edgegap.asmdef
> +        "GUID:02d6592ab05a444498a83be4f8722ca2"
Right I forgot to ask about that; The build would fail whenever I tried building the server since the asmdef didnt include the Linux 64-bit platform. I think at some point before it was included? Or it wasnt just limited to the Editor platform only, but it was updated to be Editor only at some point.
I wasnt sure whether it was fine to add the Linux platform back in, so I added another one that's specific to the runtime folder for testing and that's what's being referenced here (so the editor menu can reference the base bootstrap script). I can go fix it if it's fine to keep it all in one asmdef file.

2025-02-05 16:20 UTC, edge-marge commented on Editor/EdgegapServerBootstrapMenu.cs
> +        [MenuItem("Assets/Create/Edgegap/Server Bootstrap", priority = 35)]
![Screenshot 2025-02-05 110725](https://github.com/user-attachments/assets/78107d90-79a8-4296-9f7e-49dc3da2c7fa)

When it's 10 the Edgegap menu isnt separated in its own little section like the Mirror one (see image). I tried with a few other numbers and 35 is the first one i checked that did it, but I think 30 would work the same.

2025-02-07 15:28 UTC, edge-marge commented on Editor/EdgegapWindowV2.cs
> +            EditorPrefs.DeleteKey(EdgegapWindowMetadata.SELECTED_NETCODE_KEY_STR);
Do you mean if a script was already generated from one of the templates before deleting the key? That will still work as intended since the key is just used to pick the correct template via the editor menu.
If you mean just the bootstrap menu, then it wont be able to create the script and add it to the scene if there isnt one already there.

2025-02-20 20:57 UTC, orcist requested changes
please review and respond to my questions or change code if needed 🙏

2025-02-20 20:57 UTC, orcist commented on Edgegap.asmdef
> +        "GUID:02d6592ab05a444498a83be4f8722ca2"
sorry but I'm still not sure what this is referencing? which asset is this? why is it needed? as far as I know we only add one script to the project folder and scene, and the plugin shouldn't be used in any way in the server build itself.

2025-02-20 20:57 UTC, orcist commented on Editor/EdgegapServerBootstrapMenu.cs
> +        [MenuItem("Assets/Create/Edgegap/Server Bootstrap", priority = 35)]
thank you understood now, makes sense! :+1:

2025-02-20 20:57 UTC, orcist commented on Editor/EdgegapServerBootstrapMenu.cs
> +                            Debug.LogWarning("Could not find new script's type.");
@edge-marge how can a user select custom netcode? the plugin netcode bootstrap option should be optional, for users who currently are using Fusion 2 (not integrated yet) or a custom / different netcode solution which is not officially supported

2025-02-20 20:57 UTC, orcist commented on Editor/EdgegapWindowV2.cs
> +            EditorPrefs.DeleteKey(EdgegapWindowMetadata.SELECTED_NETCODE_KEY_STR);
okay so the user would have to pick their netcode again after they sign back in, at which point the plugin will detect the bootstrap script is present and will not recreate the file?

more questions:
- If the user follows the flow [sign out -> delete editorprefs -> sign in] will the `EdgegapServerBootstrap` game object in the active scene be duplicated?
- If the plugin gets an update with a changed version of the netcode-specific bootstrap script, does the user have to delete the script, `EdgegapServerBootstrap` game object in the active scene, and re-select their netcode to get the updated bootstrap script for their netcode?

2025-02-20 20:57 UTC, orcist commented on Runtime/EdgegapServerBootstrap.cs
> +                if (envs.Contains("ARBITRIUM_ENV_DEBUG"))
isn't `envs` a `DictionaryEntry`? shouldn't you be checking `envKey.Contains(...)` instead?

2025-02-20 20:57 UTC, orcist commented on Runtime/EdgegapServerBootstrap.cs
> +                if (envs.Contains("ARBITRIUM_ENV_DEBUG"))
please test this part of the code to see if it actually works

2025-02-21 15:40 UTC, edge-marge commented on Edgegap.asmdef
> +        "GUID:02d6592ab05a444498a83be4f8722ca2"
![Screenshot 2025-02-21 100000](https://github.com/user-attachments/assets/588514c3-9408-47e6-a114-4f7b2534e4b3)
![Screenshot 2025-02-21 100136](https://github.com/user-attachments/assets/83a13148-17ca-451d-97e5-15600c8cdaeb)
it's referencing this, which I added because the one script that's added to the project folder/scene needs to reference the abstract EdgegapServerBootstrap script it's inheriting from + the models in the runtime folder, otherwise the server build won't work.

2025-02-21 17:08 UTC, orcist commented on Edgegap.asmdef
> +        "GUID:02d6592ab05a444498a83be4f8722ca2"
could you try to remove this dependency somehow? maybe if you copied the script in the project file as well?

2025-02-25 15:51 UTC, edge-marge commented on Runtime/EdgegapServerBootstrap.cs
> +                if (envs.Contains("ARBITRIUM_ENV_DEBUG"))
`envs` is the whole dictionary, so calling `envs.Contains("ARBITRIUM_ENV_DEBUG")` checks if that specific environment variable exists and if so, logs all of the arbitrium envs. I've tested it and it works.

2025-02-25 15:58 UTC, edge-marge commented on Editor/EdgegapWindowV2.cs
> +            EditorPrefs.DeleteKey(EdgegapWindowMetadata.SELECTED_NETCODE_KEY_STR);
1) the gameObject doesn't get duplicated, no
2) the user would have to delete the bootstrap script + the gameObject in the scene, but if the editorPrefs key hasn't been deleted then they don't need to reselect the netcode, they can just use the Assets->Create->Edgegap->Server Bootstrap
3) no, but I can change it to make it do that

2025-02-25 16:16 UTC, edge-marge commented on Editor/EdgegapServerBootstrapMenu.cs
> +                            Debug.LogWarning("Could not find new script's type.");
how would the custom netcode bootstrap script even work? for the Mirror/Fishnet/Unity scripts, we're able to include the right namespace(s) in order to use access their transports/network manager and check if their values are set properly, and we know their corresponding protocols to compare with the port mappings.
I can add the Custom option in the plugin & make it add the gameObject to the scene, but I'm not sure what to do with the ServerBootstrapCustom script that would be attached to it.

2025-02-26 16:54 UTC, orcist commented
remaining questions:
- how can a user select custom netcode? the plugin netcode bootstrap option should be optional, for users who currently are using Fusion 2 (not integrated yet) or a custom / different netcode solution which is not officially supported.
- If the user follows the flow [sign out -> delete editorprefs -> sign in] will the EdgegapServerBootstrap game object in the active scene be duplicated?
- If the plugin gets an update with a changed version of the netcode-specific bootstrap script, does the user have to delete the script, EdgegapServerBootstrap game object in the active scene, and re-select their netcode to get the updated bootstrap script for their netcode?
- If the user changes their netcode selection, is the previously included bootstrap script and game object in active scene removed and replaced with a new one?

2025-02-26 16:56 UTC, orcist commented on Editor/EdgegapServerBootstrapMenu.cs
> +                return false;
When can this happen? Shouldn't it be an exception rather than a warning like this?

If you selected a netcode option and we don't have a template, our plugin is broken and the user can't do anything to fix it. We need them to contact us so an exception would be better imho.

2025-02-27 15:21 UTC, edge-marge commented
> remaining questions:
> 
>     * how can a user select custom netcode? the plugin netcode bootstrap option should be optional, for users who currently are using Fusion 2 (not integrated yet) or a custom / different netcode solution which is not officially supported.
> 
>     * If the user follows the flow [sign out -> delete editorprefs -> sign in] will the EdgegapServerBootstrap game object in the active scene be duplicated?
> 
>     * If the plugin gets an update with a changed version of the netcode-specific bootstrap script, does the user have to delete the script, EdgegapServerBootstrap game object in the active scene, and re-select their netcode to get the updated bootstrap script for their netcode?
> 
>     * If the user changes their netcode selection, is the previously included bootstrap script and game object in active scene removed and replaced with a new one?

- if the custom netcode is selected and the user tries to create the server bootstrap via the Assets->Create menu, do we simply print a log saying something along the lines of reaching out to us with the netcode they're using so that it can potentially be implemented at a later date?
- the gameObject in the scene does not get duplicated, no
- the gameObject and script would need to be deleted and re-created, yes. the netcode would only need to be re-selected if they signed out/deleted the editorPrefs, or if we changed the value that gets stored in the netcode editorPref (ex. we changed Mirror to MirrorEx in both the dropdown option and the name of the Mirror script template)
- not automatically, but if they use the Assets->Create menu again it'll update both

2025-02-27 15:29 UTC, edge-marge commented on Editor/EdgegapServerBootstrapMenu.cs
> +                return false;
makes sense. with an exception message like "Template file not found; Contact the Edgegap team about a plugin fix."?

2025-05-13 19:31 UTC, merged